# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.grpc import pretzel_ai_pb2 as pretzel__ai__pb2


class PretzelAiStub(object):
    """The mgmtd <-> pretzel-ai contract. Source of truth; mirrored into pretzel/mgmtd/grpc/.
    The mgmtd <-> pretzel-ai contract. mgmtd is the client (a person typing in the console);
    pretzel-ai is the server. Named for the service, not for one of its calls: it answers chat
    turns and it owns the tech-doc corpus behind them, so "Inference" stopped describing it. Streaming from the start: a chat turn comes back token-by-token so the console can
    render the answer as it arrives rather than after the whole thing is built.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_stream(
                '/pretzel.ai.v1.PretzelAi/Chat',
                request_serializer=pretzel__ai__pb2.ChatRequest.SerializeToString,
                response_deserializer=pretzel__ai__pb2.ChatChunk.FromString,
                )
        self.RefreshCorpus = channel.unary_stream(
                '/pretzel.ai.v1.PretzelAi/RefreshCorpus',
                request_serializer=pretzel__ai__pb2.RefreshCorpusRequest.SerializeToString,
                response_deserializer=pretzel__ai__pb2.RefreshProgress.FromString,
                )
        self.GetCorpusStatus = channel.unary_unary(
                '/pretzel.ai.v1.PretzelAi/GetCorpusStatus',
                request_serializer=pretzel__ai__pb2.CorpusStatusRequest.SerializeToString,
                response_deserializer=pretzel__ai__pb2.CorpusStatus.FromString,
                )
        self.ListDocuments = channel.unary_unary(
                '/pretzel.ai.v1.PretzelAi/ListDocuments',
                request_serializer=pretzel__ai__pb2.ListDocumentsRequest.SerializeToString,
                response_deserializer=pretzel__ai__pb2.DocumentList.FromString,
                )


class PretzelAiServicer(object):
    """The mgmtd <-> pretzel-ai contract. Source of truth; mirrored into pretzel/mgmtd/grpc/.
    The mgmtd <-> pretzel-ai contract. mgmtd is the client (a person typing in the console);
    pretzel-ai is the server. Named for the service, not for one of its calls: it answers chat
    turns and it owns the tech-doc corpus behind them, so "Inference" stopped describing it. Streaming from the start: a chat turn comes back token-by-token so the console can
    render the answer as it arrives rather than after the whole thing is built.
    """

    def Chat(self, request, context):
        """One chat turn. The reply is a stream of chunks; the final chunk has done=true and carries
        the turn-level outcome (usage, and later the AIRS scan verdict — see the old
        gateway_service.extract_scan for the shape those fields will take).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshCorpus(self, request, context):
        """--- The tech-doc knowledge base -------------------------------------------------------

        The assistant answers out of a corpus crawled from docs.paloaltonetworks.com, and Palo Alto
        republishes those docs continuously, so keeping it current is an operation the console has
        to expose rather than a one-off import. It is split in two on purpose: Check is cheap (one
        sitemap fetch) and tells the operator what a refresh would do, so Refresh is never a blind
        21,768-page download.

        Re-fetch every page the sitemap lists and keep the ones that are documents. Streams progress
        because it runs for the better part of an hour and the console holds a window open for it;
        the stream is also the cancellation channel — mgmtd stops reading and the crawl stops.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCorpusStatus(self, request, context):
        """What is in the store right now: the card's resting state and the corpus browser's tree.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDocuments(self, request, context):
        """The documents under one product/book, for the corpus browser. Titles and URLs only — the
        bodies are what the assistant reads, not what an operator scrolls.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PretzelAiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=pretzel__ai__pb2.ChatRequest.FromString,
                    response_serializer=pretzel__ai__pb2.ChatChunk.SerializeToString,
            ),
            'RefreshCorpus': grpc.unary_stream_rpc_method_handler(
                    servicer.RefreshCorpus,
                    request_deserializer=pretzel__ai__pb2.RefreshCorpusRequest.FromString,
                    response_serializer=pretzel__ai__pb2.RefreshProgress.SerializeToString,
            ),
            'GetCorpusStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCorpusStatus,
                    request_deserializer=pretzel__ai__pb2.CorpusStatusRequest.FromString,
                    response_serializer=pretzel__ai__pb2.CorpusStatus.SerializeToString,
            ),
            'ListDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDocuments,
                    request_deserializer=pretzel__ai__pb2.ListDocumentsRequest.FromString,
                    response_serializer=pretzel__ai__pb2.DocumentList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pretzel.ai.v1.PretzelAi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PretzelAi(object):
    """The mgmtd <-> pretzel-ai contract. Source of truth; mirrored into pretzel/mgmtd/grpc/.
    The mgmtd <-> pretzel-ai contract. mgmtd is the client (a person typing in the console);
    pretzel-ai is the server. Named for the service, not for one of its calls: it answers chat
    turns and it owns the tech-doc corpus behind them, so "Inference" stopped describing it. Streaming from the start: a chat turn comes back token-by-token so the console can
    render the answer as it arrives rather than after the whole thing is built.
    """

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/pretzel.ai.v1.PretzelAi/Chat',
            pretzel__ai__pb2.ChatRequest.SerializeToString,
            pretzel__ai__pb2.ChatChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RefreshCorpus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/pretzel.ai.v1.PretzelAi/RefreshCorpus',
            pretzel__ai__pb2.RefreshCorpusRequest.SerializeToString,
            pretzel__ai__pb2.RefreshProgress.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCorpusStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pretzel.ai.v1.PretzelAi/GetCorpusStatus',
            pretzel__ai__pb2.CorpusStatusRequest.SerializeToString,
            pretzel__ai__pb2.CorpusStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pretzel.ai.v1.PretzelAi/ListDocuments',
            pretzel__ai__pb2.ListDocumentsRequest.SerializeToString,
            pretzel__ai__pb2.DocumentList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
