#!/usr/bin/env python3
"""pretzel-ai-package — install the daemon on a production host.

    sudo ./pretzel-ai-package install [--prefix /opt/pretzel-ai]

This file runs standalone from inside the package. It deliberately does not import the
repository's script/utils.py: there is no repository on a production host, and there should not
be. The constants below mirror the ones there, so a change to either must be made to both.

What install does:
  1. Preflight (root / OS / python / arch / wheels present)
  2. Place src, sql and config under <prefix>
  3. Create a venv and install from the bundled wheelhouse (no network needed)
  4. Prepare /var/log/pretzel-ai and /etc/pretzel-ai/keys.env
  5. Write the systemd unit, enable it, restart, and confirm it actually answers
"""

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
import time

HERE = os.path.abspath(os.path.dirname(__file__))

DEFAULT_PREFIX = "/opt/pretzel-ai"
SERVICE_NAME = "pretzel-ai.service"
SERVICE_PATH = os.path.join("/etc/systemd/system", SERVICE_NAME)
LOG_DIR = "/var/log/pretzel-ai"
LOG_FILE = os.path.join(LOG_DIR, "pretzel-ai.log")
ENV_DIR = "/etc/pretzel-ai"
ENV_FILE = os.path.join(ENV_DIR, "keys.env")
LISTEN = "127.0.0.1:50051"

# Same shape as the repository's script/start.py. The only difference is WorkingDirectory, which
# points at the install prefix rather than a developer's home.
UNIT_TEMPLATE = """\
# {path}
# Generated by pretzel-ai-package. Hand edits are overwritten by the next install.
[Unit]
Description=Pretzel AI inference service (gRPC)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory={prefix}
Environment="PZ_PRETZEL_AI_LOG_LEVEL={log_level}"
# Keys live here, not in the repository and not in the config document. The leading '-' means a
# missing file is not an error.
EnvironmentFile=-{env_file}
ExecStart={python} -m src.main --listen {listen}
Restart=always
RestartSec=3
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
"""

ENV_TEMPLATE = """\
# pretzel-ai keys — root only (0600). Read by the systemd unit as an EnvironmentFile.
#
# A fallback, not the source. In a deployment the appliance pushes these over ApplyConfig from its
# sealed store, and a pushed key wins over anything here — an env var that outranked the console
# would mean an operator rotating a key in the UI and watching nothing happen. Fill these in only
# to run the service without an appliance in front of it.
PANW_AI_SEC_API_KEY=
PZ_PORTKEY_API_KEY=
"""


def say(msg):
    print(f"[*] {msg}")


def die(msg, hint=""):
    print(f"\n[Error] {msg}", file=sys.stderr)
    if hint:
        for line in hint.splitlines():
            print(f"        {line}", file=sys.stderr)
    sys.exit(1)


def run_cmd(cmd, msg=None, check=True):
    if msg:
        say(msg)
    r = subprocess.run(cmd)
    if check and r.returncode != 0:
        die(f"Command failed: {' '.join(cmd)}")
    return r.returncode


def manifest():
    with open(os.path.join(HERE, "MANIFEST.json")) as f:
        return json.load(f)


def _bundled_pip_wheel():
    """The pip wheel shipped in the wheelhouse, or None."""
    wh = os.path.join(HERE, "wheelhouse")
    if not os.path.isdir(wh):
        return None
    for n in sorted(os.listdir(wh)):
        if n.startswith("pip-") and n.endswith(".whl"):
            return os.path.join(wh, n)
    return None


# ── Preflight ────────────────────────────────────────────────────────────────────────────────

def preflight(mf):
    """Refuse everything that can be refused before a single file is written.

    A half-installed host is the hardest state to recover from: files are in place but the service
    will not start, and nothing tells you whether this install or the previous one is at fault."""
    if os.geteuid() != 0:
        die("Root privileges are required.", "sudo ./pretzel-ai-package install")

    # Binary wheels (psycopg_binary, grpcio) are tied to the glibc they were built against.
    built = mf.get("os", "")
    try:
        cur = {}
        with open("/etc/os-release") as f:
            for line in f:
                if "=" in line:
                    k, v = line.strip().split("=", 1)
                    cur[k] = v.strip('"')
        here = f"{cur.get('ID','?')} {cur.get('VERSION_ID','?')}"
    except OSError:
        here = "?"
    if built and here != built:
        die(f"OS mismatch: the package was built on '{built}', this host is '{here}'.",
            "Native wheels are tied to the glibc version, so they cannot be used as they are.\n"
            "Rebuild the package on a matching host.")
    say(f"OS: {here}")

    py = mf.get("python", "")
    cur_py = f"{sys.version_info.major}.{sys.version_info.minor}"
    if py and not py.startswith(cur_py):
        die(f"Python mismatch: the package targets {py}, this host has {cur_py}.",
            "Wheel filenames pin the CPython ABI, so they will not install.")
    say(f"Python: {sys.version.split()[0]}")

    wh = os.path.join(HERE, "wheelhouse")
    n = len(os.listdir(wh)) if os.path.isdir(wh) else 0
    if n == 0:
        die("The wheelhouse is empty.", "The package is incomplete. Copy it across again.")
    if not _bundled_pip_wheel():
        die("No pip wheel in the wheelhouse.",
            "The package is incomplete. Rebuild it with ./pretzel-ai package.")
    say(f"Wheelhouse: {n} wheels")

    # Actually build a throwaway venv rather than trusting that python3 exists. Debian and Ubuntu
    # ship the venv module in libpython3-stdlib but move ensurepip into python3-venv, so `python3
    # -m venv` can fail on a host where python3 is plainly present. Finding that out here costs
    # nothing; finding it out after the payload is on disk leaves a half-installed host.
    with tempfile.TemporaryDirectory() as tmp:
        probe = os.path.join(tmp, "probe")
        r = subprocess.run([sys.executable, "-m", "venv", "--without-pip", probe],
                           capture_output=True, text=True)
        if r.returncode != 0 or not os.path.isfile(os.path.join(probe, "bin", "python")):
            die("Cannot create a virtualenv on this host.",
                (r.stderr or r.stdout).strip()[:400] or
                "python3 -m venv failed.\n"
                "apt-get install -y python3-venv")
    say("Virtualenv support: OK")


def verify_files(mf):
    """Check every file against the sha256 in MANIFEST — this catches a truncated transfer."""
    bad = []
    for rel, want in mf.get("files", {}).items():
        p = os.path.join(HERE, rel)
        if not os.path.isfile(p):
            bad.append(f"{rel} (missing)")
            continue
        h = hashlib.sha256()
        with open(p, "rb") as f:
            for chunk in iter(lambda: f.read(1 << 20), b""):
                h.update(chunk)
        if h.hexdigest() != want:
            bad.append(f"{rel} (checksum mismatch)")
    if bad:
        die("Package integrity check failed:\n        " + "\n        ".join(bad[:10]),
            "The transfer may have been truncated. Copy the tarball across again.")
    say(f"Integrity: {len(mf.get('files', {}))} files verified")


# ── Install ──────────────────────────────────────────────────────────────────────────────────

def place_payload(prefix):
    os.makedirs(prefix, exist_ok=True)
    for name in ("src", "sql"):
        src, dst = os.path.join(HERE, name), os.path.join(prefix, name)
        if not os.path.isdir(src):
            continue
        # Remove before copying. On an upgrade, a module deleted in the new release would
        # otherwise survive and keep being imported — the "I fixed it but nothing changed" bug.
        if os.path.isdir(dst):
            shutil.rmtree(dst)
        shutil.copytree(src, dst)
        say(f"Placed: {dst}")

    # No config file is placed. There is not one any more: the deployment — vendors, models, the
    # guardrail, the turn shape — arrives from the appliance over ApplyConfig and is cached at
    # /etc/pretzel-ai/deployment.json. A fresh install comes up listening and mute, which is the
    # only state it can be in before the appliance has told it anything.


def make_venv(prefix):
    """Create the venv without ensurepip, then bootstrap pip from the bundled wheel.

    `--without-pip` is used unconditionally, not only where ensurepip is missing. Two paths would
    mean the common one gets tested and the fallback does not, and the fallback is exactly the
    path a bare production host takes. One path also pins pip itself to the version packaged
    here, so the install does not vary with whatever the host happened to ship.

    A pip wheel is a zip with `pip/` at its root, so it can be put on sys.path and run directly —
    that is what gets pip into a venv that has no pip yet."""
    venv = os.path.join(prefix, ".venv")
    py = os.path.join(venv, "bin", "python")
    if not os.path.isfile(py):
        run_cmd([sys.executable, "-m", "venv", "--without-pip", venv],
                msg=f"Creating virtualenv: {venv}")

    wh = os.path.join(HERE, "wheelhouse")
    pip_whl = _bundled_pip_wheel()
    # --no-index keeps pip off PyPI entirely: the host needs no network, and nothing other than
    # what was pinned at build time can slip in.
    run_cmd([py, os.path.join(pip_whl, "pip"), "install", "--quiet",
             "--no-index", "--find-links", wh, "pip", "setuptools", "wheel"],
            msg="Bootstrapping pip from the bundled wheel (offline)")

    pip = os.path.join(venv, "bin", "pip")
    run_cmd([pip, "install", "--quiet", "--no-index", "--find-links", wh,
             "-r", os.path.join(HERE, "requirements.txt")],
            msg="Installing dependencies (offline)")
    return py


def prepare_runtime_dirs():
    os.makedirs(LOG_DIR, exist_ok=True)
    os.chmod(LOG_DIR, 0o755)
    say(f"Log directory: {LOG_DIR}")

    os.makedirs(ENV_DIR, exist_ok=True)
    os.chmod(ENV_DIR, 0o755)
    if not os.path.isfile(ENV_FILE):
        with open(ENV_FILE, "w") as f:
            f.write(ENV_TEMPLATE)
        os.chmod(ENV_FILE, 0o600)
        say(f"Created key file: {ENV_FILE}  <- fill this in")
        return False
    # Leave an existing one alone. Overwriting keys an operator put there is the worst thing
    # this script could do.
    say(f"Key file already exists; leaving it untouched: {ENV_FILE}")
    return True


def write_unit(prefix, python, log_level):
    unit = UNIT_TEMPLATE.format(path=SERVICE_PATH, prefix=prefix, python=python,
                                listen=LISTEN, env_file=ENV_FILE, log_level=log_level)
    with open(SERVICE_PATH, "w") as f:
        f.write(unit)
    os.chmod(SERVICE_PATH, 0o644)
    say(f"Wrote systemd unit: {SERVICE_PATH}")


def wait_until_serving(timeout_sec=20):
    """`systemctl restart` returns as soon as the process is spawned, and Restart=always respawns
    it forever — so a daemon dying on an ImportError looks active to systemctl alone. Only a
    connection to the port proves the install worked."""
    import socket
    host, port = LISTEN.split(":")
    deadline = time.time() + timeout_sec
    while time.time() < deadline:
        alive = subprocess.run(["systemctl", "is-active", "--quiet", SERVICE_NAME],
                               check=False).returncode == 0
        if alive:
            try:
                with socket.create_connection((host, int(port)), timeout=1):
                    return True
            except OSError:
                pass
        time.sleep(0.5)
    return False


def install(args):
    mf = manifest()
    say(f"pretzel-ai package {mf.get('version','?')} (built {mf.get('built_at','?')})")
    preflight(mf)
    verify_files(mf)

    prefix = os.path.abspath(args.prefix)
    place_payload(prefix)
    python = make_venv(prefix)
    fresh_keys = not prepare_runtime_dirs()

    write_unit(prefix, python, args.log_level)
    run_cmd(["systemctl", "daemon-reload"], msg="systemctl daemon-reload")
    run_cmd(["systemctl", "enable", SERVICE_NAME], msg=f"Enabling {SERVICE_NAME}")
    run_cmd(["systemctl", "restart", SERVICE_NAME], msg=f"Starting {SERVICE_NAME}")

    if wait_until_serving():
        say(f"Answering on {LISTEN} — install complete")
    else:
        print()
        say("The daemon did not open its port. Recent log:")
        subprocess.run(["journalctl", "-u", SERVICE_NAME, "-n", "30", "--no-pager"], check=False)
        die("Install finished but the service is not up.",
            "Check the database connection and the API keys first; the log above has the reason.")

    print()
    say("Remaining steps:")
    if fresh_keys:
        print(f"      1. Fill in {ENV_FILE} (PANW_AI_SEC_API_KEY and friends)")
        print(f"      2. sudo systemctl restart {SERVICE_NAME}")
    print(f"      - Database schema: apply {prefix}/sql/*.sql in numeric order")
    print(f"      - Status: systemctl status {SERVICE_NAME}")
    print(f"      - Log:    tail -f {LOG_FILE}")


def main():
    ap = argparse.ArgumentParser(prog="pretzel-ai-package")
    sub = ap.add_subparsers(dest="cmd")
    p = sub.add_parser("install", help="install on this host")
    p.add_argument("--prefix", default=DEFAULT_PREFIX,
                   help=f"install location (default {DEFAULT_PREFIX})")
    p.add_argument("--log-level", default="info", choices=["debug", "info", "warning", "error"])
    args = ap.parse_args()
    if args.cmd != "install":
        ap.print_help()
        sys.exit(1)
    install(args)


if __name__ == "__main__":
    main()
